### ISSUE TITLE
How I can use only one language?

### ISSUE THREAD

**Issue by 1304654** [CuriousSolutions/AnyPicker#3]
There is a possibility only use one i18n eg de-DE against downloading  all languages?
eg;

<script type="text/javascript" src="src/i18n/anypicker-i18n-de-DE.js"></script>
$("#ip-de").AnyPicker(
				{
					mode: "datetime",
					dateTimeFormat: "MMM dd, yyyy",
					lang: "de-DE",
					onInit: function()

Because it does not work.

**Comment by nehakadam** [comment]
You can use "dist/i18n/anypicker-i18n-de.js" to include only "de" language and set 

```
$("#ip-de").AnyPicker(
{
    mode: "datetime",
    dateTimeFormat: "MMM dd, yyyy",
    lang: "de",
});
```

**Comment by 1304654** [comment]
There is the possibility of adding cultures?

**Comment by nehakadam** [comment]
Do you want to add language variation based on culture? For example, in AnyPicker there is Austrian German as "de-at". So you can add a variation and you can even change name of language in i18n files. So you can add any string as per cultural variation.
