### ISSUE TITLE
AnyPicker dynamic register functionality 

### ISSUE THREAD

**Issue by projectsphonegapdev1** [CuriousSolutions/AnyPicker#4]
We have a dynamic div for which we want to register date time picker at runtime and we also want to open that date time picker on a button click. So, please suggest as how can we achieve this? 

when a particular view renders we are using this code:
`$('#MBCControlItem' + Id).AnyPicker(	{  mode: "datetime",   dateTimeFormat: "hh:mm aa" });`
At present, on click of it, it generates multiple dynamic "anypicker" divs,

**Comment by nehakadam** [comment]
This is happening because with a dynamic container, AnyPicker may be getting initialized more than once on the same element.

As a quick fix you can use `$('#MBCControlItem' + Id).AnyPicker("destroy");`, while hiding the container in which you are initializing AnyPicker.
