### ISSUE TITLE
How I can make the biggest year is the current year

### ISSUE THREAD

**Issue by maplehsu** [CuriousSolutions/AnyPicker#5]
I found iStepYears to set the current age of 50 * / 2 to set up, but can not set the maximum is the current year alone, do not know how to set up, because I was just learning js, also want to ask. I am Chinese Chinese is not very good, so use the translator to write these issues

**Comment by nehakadam** [comment]
Following plugin parameters may be useful. Please go through documentation which is available with AnyPicker repo -
`maxValue` - set maximum date
`minValue` - set minimum date
`maxYear` - set maximum year

**Comment by maplehsu** [comment]
thk My English is not good, you also can understand me, really is too happy.

**Comment by maplehsu** [comment]
Can I make a friend with you A great god

**Comment by nehakadam** [comment]
It's good to hear that your problem is solved. You can contact us any time if you have any issue. ☺

**Comment by maplehsu** [comment]
这样联系，太麻烦了，你有 微信吗 或者gmail

**Comment by maplehsu** [comment]
Such contact, too much trouble, you have WeChat Or gmail

**Comment by nehakadam** [comment]
You can ask your queries on nehakadam9@gmail.com.

**Comment by maplehsu** [comment]
ok..~ thk

**Comment by artsnr1** [comment]
@nehakadam maxYear is not working. Kindly point out the mistake
```
        mode: "datetime",
        inputDateTimeFormat: "DDD, d MMM yyyy hh:mm AA",
        dateTimeFormat: "MMM dd yyyy hh:mm AA",
        rowsNavigation: "scroller+buttons",
        intervals: { h: 1, m: 5 },
        maxYear: 2018,
```
Also I have tried  YY format:
```
        mode: "datetime",
        inputDateTimeFormat: "DDD, d MMM YY hh:mm AA",
        dateTimeFormat: "MMM dd YY hh:mm AA",
        rowsNavigation: "scroller+buttons",
        intervals: { h: 1, m: 5 },
        maxYear: 2018,
```
